name: CI

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Installer PHP et extensions
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.3'
                  extensions: mbstring, intl, pdo, pdo_mysql

            - name: Installer les dépendances Composer
              run: composer install --prefer-dist --no-progress

            - name: Vérifier le code avec PHP_CodeSniffer
              run: vendor/bin/phpcs src/
              continue-on-error: true

            - name: Corriger le code avec PHP_CodeSniffer (phpcbf)
              run: vendor/bin/phpcbf src/
              continue-on-error: true

    test:
        runs-on: ubuntu-latest

        env:
            APP_SECRET: '$ecretf0rt3st'
            DATABASE_URL: postgresql://postgres:root@localhost:5434/ecommerce
            KERNEL_CLASS: 'App\Kernel'
            JSONSERVER_URL: 'http://localhost:3001'
            APP_ENV: 'test'

        services:
            postgres:
                image: postgres
                env:
                    POSTGRES_PASSWORD: root
                    POSTGRES_USER: postgres
                    POSTGRES_DB: ecommerce_test
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
                ports:
                    - 5434:5432

        steps:
            - uses: actions/checkout@v4

            - name: Démarrer json-server
              run: cp docker/data.origin.json docker/data_test.json && npx json-server --watch docker/data_test.json --port 3001 &

            - name: Installer PHP et extensions
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.3'
                  extensions: mbstring, intl, pdo, pdo_mysql

            - name: Installer les dépendances Composer
              run: composer install --prefer-dist --no-progress

            - name: Générer une migration Doctrine
              run: php bin/console doctrine:migrations:diff --no-interaction

            - name: Exécuter les migrations Doctrine
              run: php bin/console doctrine:migrations:migrate --no-interaction

            - name: Lancer les tests Pest
              run: vendor/bin/pest
              continue-on-error: false
